version: 0.2
phases:
  pre_build:
    commands:
      - echo "Copying files to the respective S3 locations"
  build:
    commands:
      - echo "copying airflow_dag to dag folder"
      - aws s3 cp airflow_dag.py s3://food-delivery-project-airflow/dags/
      - echo "copying New airflow_dag to dag folder"
      - aws s3 cp airflow_dag_new.py s3://food-delivery-project-airflow/dags/
      - echo "copying requirements file to s3 bucket"
      - aws s3 cp requirements.txt s3://food-delivery-project-airflow/ 
      - echo "copying pyspark script to s3 folder"
      - aws s3 cp pyspark_job.py s3://pyspark-scripts-for-projects/food-delivery/pyspark-scripts/
  post_build:
    commands:
      - echo "Deployment complete!"